//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int MaCong { get; set; }
        public Nullable<int> SoGioLam { get; set; }
        public Nullable<int> SoGioNghi { get; set; }
        public Nullable<int> LuongCoBan { get; set; }
        public Nullable<int> SoGioLamYeuCau { get; set; }
        public Nullable<int> SoGioNghiToiDa { get; set; }
        public string ThoiGianBD { get; set; }
        public string ThoiGianKT { get; set; }
    }
}
