//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoCa
    {
        public int MaGiaoCa { get; set; }
        public Nullable<int> SoTienBanGiao { get; set; }
        public Nullable<int> SoTienThuDuoc { get; set; }
        public Nullable<int> SoTienCatGiu { get; set; }
        public string GhiChu { get; set; }
        public string MaCaLam { get; set; }
        public string MaChamCong { get; set; }
    }
}
