//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int SoHD { get; set; }
        public string MaNV { get; set; }
        public string NgayLap { get; set; }
        public string MaKH { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<int> TienKhachDua { get; set; }
        public Nullable<int> TienGuiKhach { get; set; }
        public Nullable<int> TongTienKM { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    }
}
