//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MucHangKhachHang
    {
        public int MaMucHang { get; set; }
        public string TenMucHang { get; set; }
        public string ChietKhauTheoHang { get; set; }
        public Nullable<int> DiemYeuCau { get; set; }
    }
}
